- app/assets/stylesheets/layout/helper-classes.scss
- app/assets/stylesheets/layout_components/receipt-summary.scss
- app/assets/stylesheets/media_queries/mobile-and-tablet.scss
- lib/ama/styles/version.rb
🎨 
* added some helpers to I can make mobile-only changes (for payment pages)
https://github.com/amaabca/membership/pull/717 - payment changes
* changed summary page image to be left-aligned on mobile
> every single form has extra white space on the right on mobile

- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/foundation_and_overrides.scss
- lib/ama/styles/version.rb
:art:
Added flexbox the other day to ama_styles and it broke the positioning of the logo on mobile so i'm just removing it and I'll revisit getting it added correctly later.
> removing flexbox because it broke mobile logo position

- app/assets/stylesheets/layout/helper-classes.scss
> Adds margin top to mobile only

- app/assets/stylesheets/layout_components/index.scss
- app/assets/stylesheets/layout_components/spinner.scss
- lib/ama/styles/version.rb
:art:
* Move the spinner css from automotive app because this will be share
across all apps.
> Add the new spinner

- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/layout_components/index.scss
- app/assets/stylesheets/layout_components/notices.scss
- app/assets/stylesheets/layout_components/notification.scss
- app/assets/stylesheets/layout_components/right-sidebar.scss
- app/assets/stylesheets/layout_components/siteheader.scss
- spec/dummy/config/initializers/assets.rb
:art:
This is the styling for the new notification centre. Relates to this PR with the HTML markup in ama_layout https://github.com/amaabca/ama_layout/pull/202.
> Vsts 438 design

- PULL_REQUEST_TEMPLATE.md
- lib/ama/styles/version.rb
:art:
Adding our new PR checklist!
https://amaabca.visualstudio.com/dx_technical_debt/_workitems?id=1246&_a=edit
> add PR checklist

- app/assets/stylesheets/layout_components/content-toggle.scss
- lib/ama/styles/version.rb
:art:
Moving one of the gift classes to here
> Add class gifts

- ama_styles.gemspec
- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/foundation_and_overrides.scss
- app/assets/stylesheets/layout_components/siteheader.scss
- lib/ama/styles/version.rb
:art: :elephant:
This is to update the version of foundation to 6.4.1.2
Only issue I found after the update was that our links in the top nav were not correctly aligning with the bell icon anymore, so I adjusted the line-height on those elements.
Zoie also turned off the contrast warnings from foundation.
https://amaabca.visualstudio.com/dx_technical_debt/_workitems?id=926&_a=edit
~~- [ ] I've proof-read all text for legibility, proper grammar, punctuation, and capitalization (titlecase).~~
> Vsts 926 update foundation

- ama_styles.gemspec
- lib/ama/styles/internal/hipchat.rb
- lib/ama/styles/version.rb
> Update gems as much as possible as per Gemnasium report.

- app/assets/stylesheets/layout_components/comparison-radios.scss
- lib/ama/styles/version.rb
It looks like I inadvertently removed a style needed for our existing radio comparison buttons. This PR adds it back in. 
🎨 
> Adds comparison radio styles. 

- app/assets/stylesheets/layout_components/forms.scss
> updates code to BEM standards

- app/assets/stylesheets/layout_components/tabs.scss
- lib/ama/styles/version.rb
🎨  Fixes some of the issues with the tabs that makes then resize when you click on them
needed for driver ed (vsts 3634)
> De tabs updates

- app/assets/stylesheets/layout/helper-classes.scss
- app/assets/stylesheets/layout_components/forms.scss
- app/assets/stylesheets/media_queries/mobile.scss
- lib/ama/styles/version.rb
🎨 
adds some helper classes, mostly for styling things differently depending on screen size, fixes a bug with the date inputs having too much margin
> Adding text helper class

- app/assets/stylesheets/layout_components/comparison-radios.scss
- lib/ama/styles/version.rb
🐘 from @zoiec 
https://amaabca.visualstudio.com/driver_education_backlog/_workitems?id=5081&_a=edit
updates version number to match earlier changes. 
> Vsts 5081 customer card

- app/assets/stylesheets/layout_components/sections.scss
- lib/ama/styles/version.rb
:art:
adds the smoke modifier to section__content (previously it was only on section-content)
> adding smoke bg content section

- .simplecov
- lib/ama/styles/version.rb
:elephant:
* Simplecov made a breaking change to prevent wildcards in
their string filters. This was causing the test suite to
fail due to "lack of coverage".
* Simply hardcode the filter so we don't have to use a wildcard
to filter coverage.
SEE: https://github.com/colszowka/simplecov/pull/616
- ~I've added new components to the style guide (or have a PR in to add them).~
> Fix Test Suite

- app/assets/stylesheets/layout_components/member-card.scss
- lib/ama/styles/version.rb
:art:
Adding class for displaying coverage on temporary print card screen.
- ~[ ] I've added new components to the style guide (or have a PR in to add them).~
- ~[ ] I’ve linked to any relevant VSTS tickets~
> Add coverage class printcard

- app/assets/stylesheets/layout_components/buttons/button-grouping.scss
- lib/ama/styles/version.rb
🎨 
- added new background color, and slight drop shadow, to white button-grouping hover
VSTS: https://amaabca.visualstudio.com/DX_UX_Bugs/_workitems/edit/14154
- [] I've added new components to the style guide (or have a PR in to add them).
> VSTS - 14154  - add hover colour to white button groupings

- ama_styles.gemspec
- lib/ama/styles/internal/chat.rb
- lib/ama/styles/internal/commands/deploy.rb
- lib/ama/styles/version.rb
🐘
- This update allows deployment messaging to enable lita server status on slack
- locked res-client-jogger to 0.35
https://amaabca.visualstudio.com/red_tech_debt/_workitems/edit/14774
~- [ ] I've added new components to the style guide (or have a PR in to add them).~
~- [ ] I've tested on mobile, tablet, and desktop, as well as across all of the browsers we support.~
> VSTS -14774 - Update Deployment Messaging for compatibility with lita-server_status 

- app/assets/stylesheets/layout/helper-classes.scss
- lib/ama/styles/version.rb
- add &--mobile to .left
- add a .no-float to remove floats
- add &--mobile to .inline-block
🎨 
VSTS: https://amaabca.visualstudio.com/membership_backlog/_workitems/edit/14885
> VSTS - 14885 

- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/version.rb
[VSTS 14659](https://amaabca.visualstudio.com/roadside_backlog/_workitems/edit/14659)
This PR coincides with the work being done in automotive on branch [vsts14659-three-file-inputs-coffeescript](https://github.com/amaabca/automotive/pull/176). 
It styles the inputs that allow users to upload multiple documents to automotive reimbursements. 
I will have to add this to the styleguide after the fact.
> VSTS 14659 File upload styles

- ama_styles.gemspec
- lib/ama/styles/version.rb
🐘 
Update rest-client-jogger gem
REF: https://amaabca.visualstudio.com/red_tech_debt/_workitems/edit/15017
> Update client-jogger gem.

- lib/ama/styles/internal/environment.rb
- lib/ama/styles/version.rb
* Change to use new envs for the styles deploy IAM user.
VSTS_19104](https://amaabca.visualstudio.com/red_tech_debt/_workitems/edit/19104)
🐘
> Rotate the styles user keys

- app/assets/stylesheets/layout_components/accordions.scss
- lib/ama/styles/version.rb
- Remove an unused hover effect
- Add new styles for an accordion arrow image
- Add border to top and bottom of accordion
- Remove the background color
- Change the hover color for the accordion header text
🎨 
Rewards: https://stage-rewards.ama.ab.ca/transactions
Insurance: https://stage-insurance.ama.ab.ca/
VSTS: https://amaabca.visualstudio.com/rewards_backlog/_workitems/edit/19927
> VSTS-19927 - Restyle Accordion

- app/assets/stylesheets/layout_components/accordions.scss
- lib/ama/styles/version.rb
- fix arrow positioning on accordion
- remove underline from focus on accordion text
VSTS: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/85
> Accordion Arrow Styles fix

- app/assets/stylesheets/webfonts/knockout-font.scss
- lib/ama/styles/version.rb
- Remove leading "/" in font path name
🐘 
VSTS:https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/251
> VSTS-251 - knockout broke

- app/assets/stylesheets/layout_components/buttons/buttons.scss
- lib/ama/styles/version.rb
- remove the `float: right` from the button--green class
VSTS:https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/56
🐘 
> VSTS-562 - Remove Float From Green Buttons

- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/version.rb
- Add the class `.checkbox-terms` and the accompanying declaration for padding and borders.
- Increase version
🎨
ADO Link - https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/1111
> ADO-1111 - Fix Checkboxes that Contain Terms and Conditions

- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/version.rb
added transitions and hover effects to give our radio buttons more
interest.
🎨
To test this change run branch ado-4005 on ama_layout_site by running rails server and going to localhost:3000
http://localhost:3000/form_components/radios
-
ADO LINK:https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/4005
> ADO-4005 animate radio buttons in online account

- app/assets/stylesheets/layout_components/buttons/button-grouping.scss
- lib/ama/styles/version.rb
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/7323
This PR makes it possible to vertically align content within red boxes. 
See on staging: https://stage-automotive.ama.ab.ca/
Create an appointment in staging so that the red button will change and you'll be able to see where i've applied this styling.
> Ado 7323 - EOP: Integrate with PTA Lookup to Be Able to Show PTA in automotive

- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/layout/helper-classes.scss
- app/assets/stylesheets/layout/variables.scss
- app/assets/stylesheets/layout_components/accordions.scss
- app/assets/stylesheets/layout_components/buttons/buttons.scss
- app/assets/stylesheets/layout_components/card.scss
- app/assets/stylesheets/layout_components/comparison-radios.scss
- app/assets/stylesheets/layout_components/forms.scss
- app/assets/stylesheets/layout_components/legends/legends.scss
- app/assets/stylesheets/layout_components/member-info-card.scss
- app/assets/stylesheets/layout_components/progress-bar.scss
- app/assets/stylesheets/layout_components/responsive-table.scss
- app/assets/stylesheets/layout_components/tables.scss
- lib/ama/styles/version.rb
:art: 
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/8626
Mostly makes font sizes more consistent. Buttons were already mostly tiered, so just added the one that wasn't.
> adding variable tiering for buttons and font sizes

- CODEOWNERS
🐘 
Adding CODEOWNERS file
REF: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/83
> ADO - 83 Add CODEOWNERS file.

- app/assets/stylesheets/v2/layout_components/buttons/button-grouping.scss
- app/assets/stylesheets/v2/layout_components/features.scss
- app/assets/stylesheets/v2/webfonts/ama-icon-font.scss
- app/assets/stylesheets/v2/webfonts/knockout-font.scss
- app/assets/stylesheets/v2/webfonts/wisdom-font.scss
- app/assets/stylesheets/v3/layout_components/buttons/button-grouping.scss
- app/assets/stylesheets/v3/layout_components/features.scss
- app/assets/stylesheets/v3/webfonts/ama-icon-font.scss
- app/assets/stylesheets/v3/webfonts/knockout-font.scss
- app/assets/stylesheets/v3/webfonts/wisdom-font.scss
- lib/ama/styles/version.rb
See: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/12956
* use version prefixes for any asset-url helpers as they
are not relatively pathed
> ADO 12956: Versioned Assets

- app/assets/stylesheets/v3/_settings.scss
- app/assets/stylesheets/v3/layout/variables.scss
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/12960
🎨
- This PR sets some of the initial variable and settings in ama_styles. 
- @ryan-reddekopp is looking into setting our base font size and rem units, so that will be coming in a subsequent PR.
- I have not made any changes to variables for specific components, we can tackle that on the relevant cards. 
- This is just a first crack at it, we can edit and update these as we see fit, it is just to get the ball rolling!
> Initial global styles

- app/assets/stylesheets/v3/layout_components/promo-block.scss
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/12960 :art:
Updates styles for promo blocks.
New Styles: 
Old Styles:
> new styles for promo blocks

- app/assets/stylesheets/v3/layout/helper-classes.scss
- app/assets/stylesheets/v3/layout_components/tables.scss
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/12960
Updates table styles. Note: because the markup for our tables is not consistent between apps, some tables will show a grey background for the header and then the first row, this will have to be fixed in phase 2.
New Style:
Old Style:
> adding new table styles

- app/assets/stylesheets/v3/layout_components/reveal-modal.scss
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/12960
Styles the modals.
New style:
Old Style:
> Ado12960 modals

- app/assets/stylesheets/v3/layout/helper-classes.scss
- app/assets/stylesheets/v3/layout_components/graph.scss
- app/assets/stylesheets/v3/layout_components/icon-group.scss
- app/assets/stylesheets/v3/webfonts/ama-icon-font.scss
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/12959
Styles the graph and icon group.
New Style:
Old Style:
> Ado 12959 graphs

- app/assets/stylesheets/v3/layout/variables.scss
- app/assets/stylesheets/v3/layout_components/right-sidebar.scss
- lib/ama/styles/version.rb
restyled the notification centre to look like the new marketing mockups
-added a drop-shadow variable to the variables doc
🎨
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13538
> ADO-13538 Notification centre restyle

- app/assets/stylesheets/v3/layout_components/indented-list.scss
- app/assets/stylesheets/v3/layout_components/link-list.scss
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/12959
Styles our link lists and indented lists. Note: removes the borders from the "link-list--bordered" class, but I've noted that as a phase 2 change.
New Styles:
Old Styles:
> Ado 12959 lists

- app/assets/stylesheets/v3/layout_components/right-sidebar.scss
- lib/ama/styles/version.rb
-remove the notifications borders
-change the color of the active notification to a light brand blue colour
🎨
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13538
> ADO-13538 notifications

- app/assets/stylesheets/v3/layout/base.scss
- app/assets/stylesheets/v3/layout/helper-classes.scss
- app/assets/stylesheets/v3/layout_components/notices.scss
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13537
Styles notices, and adds bold to links.
New Style
Old Style
> styling notices + links

- app/assets/stylesheets/v3/_settings.scss
- app/assets/stylesheets/v3/layout/variables.scss
- app/assets/stylesheets/v3/layout_components/sections.scss
- app/assets/stylesheets/v3/layout_components/side_nav.scss
- app/assets/stylesheets/v3/layout_components/siteheader.scss
- lib/ama/styles/version.rb
[ADO 13009](https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13009) 🎨  
This PR has a corresponding set of API changes which contain some markup changes. (https://github.com/amaabca/api/pull/630)
I left the component block name as `side-nav` for now in an effort to try and preserve class names for testing purposes. If as a design team we don't think this is worthwhile, I can go back in and revise the name to be `top-nav`.
Some suggestions on what to review (Changes are on staging, but will **only have the corresponding API changes in the registries application**):
- A logged in member
- A logged in non-member
- Someone registering for a membership - (This _will_ appear wrong, and will need to be fixed within the membership application.)
To be completed by the person who opens the PR. …
> Side Nav Styles

- Rakefile
- ama_styles.gemspec
- app/assets/stylesheets/v3/layout_components/accordions.scss
- lib/ama/styles/version.rb
- Make arrow centre-aligned with a 16px top margin at small breakpoints
- Decrease the size of the Accordion header font from 1.5x to 1.25x for
small breakpoints
Mobile:
Tablet:
Mobile:
Tablet:
🎨
ADO LINK:https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13865
> ADO-13865 Accordion Arrow Fixes

- app/assets/stylesheets/v3/layout_components/forms.scss
- lib/ama/styles/version.rb
- Change the padding on the error states to be closer to the new www
site.
- Change the corners to all be 9px radius
🎨
ADO LINK:https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13865
> ADO-13865 Fix rounded corners on all errors

- README.md
- lib/ama/styles/version.rb
🐘
- Added the fontawesome all.js and the minified version to be included as needed
in applications
- updated version
- updated readme.md
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_boards/board/t/Red%20Team/Stories/?workitem=14090
> ADO-14090 - Add the newest fa-all js

- app/assets/stylesheets/v3/layout_components/chat-widget.scss
- lib/ama/styles/version.rb
[ADO 13865](https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13865)
Styling the chat widget.
> click to chat styling for v3

- lib/ama/styles/globals.rb
- lib/ama/styles/version.rb
- spec/lib/ama/styles/resolver_spec.rb
See: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/14330
* set default version to v3
> ADO 14330: WWW Launch

- app/assets/stylesheets/v3/layout/variables.scss
- app/assets/stylesheets/v3/layout_components/side_nav.scss
- app/assets/stylesheets/v3/layout_components/siteheader.scss
- lib/ama/styles/version.rb
🎨
- increased the height of the header
- increased font size of links
- adjusted font size to accommodate viewport under 1600px wide
- moved links and OA logo to accommodate new header height
- changed colour of top-header to match the colour in www
- changed colour of links to match colour in www
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/14338
> ADO-14338 OA header fixes

- app/assets/stylesheets/v3/layout_components/side_nav.scss
- lib/ama/styles/version.rb
As part of https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/14685
Adds a larger width when multiple columns are needed in the top nav dropdown
> small fix for nav in style guide

- app/assets/stylesheets/v2/layout_components/chat-widget.scss
- lib/ama/styles/version.rb
- add CSS to remove the minimize and close buttons in the Chat feature
for the Practicce Exam app
- Update Version number
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/16276
🎨 
> ADO-16276 DEPEA V2 Chat Widget Changes

- app/assets/stylesheets/v3/layout/variables.scss
- app/assets/stylesheets/v3/layout_components/responsive-table.scss
- lib/ama/styles/version.rb
🎨
- Completely rewrite the css for the responsive tables
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/16780
> ADO-16780 Better table markup and design

- app/assets/stylesheets/v3/layout_components/side_nav.scss
- lib/ama/styles/version.rb
🎨 
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/16910
Fixes the drop-shadow so it is behind the sub-nav.
> Ado 16910 drop shadow

- app/assets/stylesheets/v3/layout_components/responsive-table.scss
- lib/ama/styles/version.rb
🎨
- Adjust the breakpoints for the new tables so they are easier to read
on tablet devices
ADO LINK:https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/17448
> ADO-17448 Adjust breakpoints for tables

- app/assets/stylesheets/v3/layout/helper-classes.scss
- lib/ama/styles/version.rb
🎨
- Add a float right and left for tablet-down
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/17449
> ADO-17449 fix tables in registries

- .github/workflows/ci.yml
- ama_styles.gemspec
- app/assets/stylesheets/v3/layout/helper-classes.scss
- app/assets/stylesheets/v3/layout_components/forms.scss
- config/application.rb
- lib/ama/styles/version.rb
- spec/dummy/config/application.rb
🎨
- Added padding to the checkbox text
- changed the size of the checkmark box to better align the box and text
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/17635
> ADO-17635 Fix checkboxes in OA

- app/assets/images/airplane.svg
- app/assets/images/car-accident.svg
- app/assets/images/home-key.svg
- app/assets/images/island.svg
- app/assets/images/tire-change.svg
- lib/ama/styles/version.rb
🎨
- update images...
airplane.svg
car-accident.svg
home-key.svg
island.svg
tire-change.svg
- increase version number
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/18456
> ADO-18456 create new icon and reconfigure reimbursement form page

- app/assets/stylesheets/v2/layout/helper-classes.scss
- lib/ama/styles/version.rb
See: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/19604
* allow for transparent backgrounds. Helpful for our iframed
login and potentially other future features
> ADO 19604: Transparent Background Helper

- .github/workflows/ci.yml
- .rubocop.yml
- Dangerfile
- app/assets/stylesheets/v3/layout_components/buttons/button-grouping.scss
- app/assets/stylesheets/v3/layout_components/callouts/callouts.scss
- lib/ama/styles/version.rb
* Create a `button-grouping__round-icon` element that can
be used for image icons when placed in marketing materials.
* Create a `button-grouping__flex` element that uses flexbox
to layout the content of the button group. This allows for
a much simpler and consistent experience to align/center the
content of the box.
SEE: [AB#31519](https://dev.azure.com/AMA-Ent/ccb94584-03a5-426b-9211-75a5115f75dc/_workitems/edit/31519)
> AB#31519 - Round Icon | Button Grouping
