amaabca/ama_styles

- .rubocop.yml
- lib/ama/styles/globals.rb
- lib/ama/styles/internal/deployment.rb
- lib/ama/styles/version.rb
:elephant:
* For performance, tell S3 to set a far-future cache expiration of
30 years in the future. This helps optimize delivery by letting
clients cache the content (almost) indefinitely. If any file
changes, the sprockets digest of the file will change - effectively
breaking the cache.
* Slightly bump allowed class length in rubocop.
> Set A Far Future Cache Expiration

- app/assets/stylesheets/layout_components/callouts/quote-callout.scss
- lib/ama/styles/version.rb
So it doesn't squish in forcing text to wrap in ugly ways.
Before: 
After:
🎨 
https://ama-digital.myjetbrains.com/youtrack/issue/INSAQ-1027
> Specifying quote callout width

- app/assets/stylesheets/layout/helper-classes.scss
- lib/ama/styles/version.rb
- This allows the margin/padding to be set to 0px only for desktop layouts, while leaving it as the base value for mobile.
- Used for navigation buttons in Insurance.
- Also using $base-padding instead of $base-margin for padding values,
as they should be.
🎨
> Adding mobile overrides for mb0 and pb0 classes

- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/version.rb
- Existing styles assume a year/month/day set of inputs, so the layout breaks when day element is removed.
- New class is applied to the div wrapping the date inputs.
Desktop:
Mobile:
https://ama-digital.myjetbrains.com/youtrack/issue/INSGW-119
🎨
> Added class to properly align month/year date inputs

- app/assets/stylesheets/layout_components/links.scss
- lib/ama/styles/version.rb
- When class is used inside a modal, the underline gets overridden. Adding important so you get the styles you expect
:art:
> Forcing white links to be underlined

- app/assets/stylesheets/layout_components/footer.scss
- app/assets/stylesheets/layout_components/siteheader.scss
:art:
* Road reports uses ama_styles, but does not have a page footer.
* The off-canvas-wrapper class has an :after attribute on it to
set the height of a page footer for our sticky footer.
* Because roadreports has no footer, add a :not css pseudoclass
to conditionally add the footer extra space only when
neccessary.
SEE: https://ama-digital.myjetbrains.com/youtrack/issue/RREPORT-1110
> RREPORT-1110 - Road Reports Scroll on Safari

- app/assets/stylesheets/layout_components/buttons/button-toggle.scss
- app/assets/stylesheets/layout_components/siteheader.scss
- lib/ama/styles/version.rb
:art:
* Road reports uses a `top-nav-offset` class to provide extra space
for the actual page on desktop screen sizes.
* On smaller sizes, the navigation components are hidden so we must also
hide the offset spacer to prevent page scrolling.
SEE: https://ama-digital.myjetbrains.com/youtrack/issue/RREPORT-1110
> RREPORT-1110 - Road Reports Scrolling in Safari

- app/assets/stylesheets/layout_components/buttons/button-toggle.scss
- app/assets/stylesheets/layout_components/footer.scss
- app/assets/stylesheets/layout_components/legends/legend-map.scss
- app/assets/stylesheets/layout_components/maps.scss
- app/assets/stylesheets/layout_components/siteheader.scss
- lib/ama/styles/version.rb
:art:
__Take Two__
* A first approach was used previously to remove the nav-offset
in road reports on mobile. This worked for the most part, but
due to existing css/markup, all overlay elements had to be pushed
down.
* Revert the recent changes described above.
* Instead, we need to set the off-canvas-wrapper height to 100% for the
`no-footer` variant so that the page does not scroll on mobile.
SEE: https://ama-digital.myjetbrains.com/youtrack/issue/RREPORT-1110
> RREPORT-1110 - Mobile Scrolling

- app/assets/stylesheets/layout_components/comparison-radios.scss
- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/version.rb
:art:
* The coverage selection page has high complexity due to the
number of elements that need to be equalized in height.
* Take an alternate approach and remove the number of equalizer
elements on the page. We have to clearfix the container element
becuase all of its children are floated - yet we want accurate
height.
* Remove the after pseudo element on the checkbox inputs/labels.
It was adding an unwanted transition and extra space for content.
* Issues like above will be fixed after a few markup changes.
SEE: https://ama-digital.myjetbrains.com/youtrack/issue/MEMBR-1490
> MEMBR-1490 - DM Promo Premier Form

- ama_styles.gemspec
- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/layout/mixins-grid.scss
- app/assets/stylesheets/layout/variables.scss
- app/assets/stylesheets/layout_components/forms.scss
- app/assets/stylesheets/layout_components/siteheader.scss
- lib/ama/styles/version.rb
:art:
upgraded ama_styles to newest version of foundation 6.3.1.0
Fixed mixin grid because foundation made some changes that deprecated the code we were using.
had to change $base-font-size to a pixel value because with the rem value it kept throwing an error.
Added some styling to hide the automatic styling the drop down forms by the browser so we could display our custom styling.
After updating the space below the header changed, so I had to adjust the value of top-nav-offset.
> Upgrade foundation 6.3

- app/assets/stylesheets/layout_components/footer.scss
- lib/ama/styles/version.rb
:art:
* The upgrade to Foundation 6.3 broke our sticky footer. The reason
is that the `html` and `body` no longer have 100% height.
* Bump version.
> Fix Sticky Footer

- app/assets/stylesheets/layout_components/comparison-radios.scss
- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/version.rb
:art:
our membership form fields were not 100% width on mobile. This PR is to fix that, as well as the width of the comparison radios.
https://ama-digital.myjetbrains.com/youtrack/issue/OAUTH-1193
before:
Now with this fix:
> adding media queries to fix mobile forms in membership

- ama_styles.gemspec
- lib/ama/styles/version.rb
- lib/ama_styles.rb
:elephant:
* Even though we only *officially* support the last 2 releases of
iOS (currently 9 and 10), we sometimes get support requests for
users on older devices.
* Because of Foundation's use of `transform` CSS attributes in
off canvas, older browsers were causing the offcanvas nav
to overlap with the majority of the page. This completely
made all our websites unusable.
* Use `autoprefixer-rails` to automatically add the appropriate
vendor prefixes for CSS attributes for compatibility with the
majority of browsers.
SEE: https://amaabca.visualstudio.com/membership_backlog/_workitems?id=524
> VSTS-524 - Increase Compatibility For Older Browsers

- app/assets/stylesheets/layout_components/callouts/price-callout.scss
- app/assets/stylesheets/layout_components/content-toggle.scss
- lib/ama/styles/version.rb
:art:
This adds the styling needed to create the blue toggle box to display what kinds of discounts they got.
> adding styling for insurance discounts toggle box

- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/internal/hipchat.rb
- lib/ama/styles/version.rb
:art: :elephant:
* Foundation deprecated the `header-sizes` variable name with
version `6.3`. The new name is `header-styles` and it uses a
slightly different format.
* Fix a SASS deprecation warning about extending from the compound
selector `small.error`. This will be removed in a future version
of SASS.
* Use version 1 of the HipChat API. Version 2 does not work properly with the hipchat gem.
SEE: https://github.com/zurb/foundation-sites/pull/9419
SEE: https://github.com/sass/sass/issues/1599
SEE: https://amaabca.visualstudio.com/membership_backlog/_workitems?id=1735
> Fix Foundation Deprecations

- app/assets/stylesheets/layout_components/comparison-radios.scss
Part of VSTS: https://amaabca.visualstudio.com/driver_education_backlog/_workitems?id=1735&_a=edit
This PR creates new styles which will allow us to create comparison radios which do not rearrange on mobile by using the class `.comparison-radios__radio-btn--stacked` instead of `.comparison-radios__radio-btn--centered`
These new styles should not have any effect on existing comparison radios. 
Currently being used on https://github.com/amaabca/driver_ed_public/pull/21
🎨 
New Styles | Old Styles
> Adds styles to comparison radios so they stack on mobile

- app/assets/stylesheets/layout_components/notification.scss
- lib/ama/styles/version.rb
:art:
* On the desktop view, our notification badge wasn't positioned
properly.
* Use percentage to position the badge into the correct location.
- ~I've added new components to the style guide (or have a PR in to add them)~
- ~I’ve linked to any relevant VSTS tickets~
> Fix Notification Badge Position

- app/assets/stylesheets/layout/helper-classes.scss
- lib/ama/styles/version.rb
This PR adds a bottom padding to the hint in our forms. 
🎨
> adds bottom padding to hint

- app/assets/stylesheets/layout_components/buttons/buttons.scss
- lib/ama/styles/version.rb
This PR adds `text-decoration: none;` to the `.button` hover state. Currently, this functionality exists on our buttons which are created using `<input>` tags, but it does not exist on buttons created using `<a>` tags. The style currently exists on the button, but not the hover state. 
I'm rolling this fix into this [VSTS card here.](https://amaabca.visualstudio.com/driver_education_backlog/_workitems?id=2056&_a=edit)
🎨 
Hover before (grey button):
Hover after:
> Add text-decoration-none to button hover state

- app/assets/stylesheets/layout_components/buttons/button-grouping.scss
- app/assets/stylesheets/layout_components/forms.scss
- app/assets/stylesheets/layout_components/sections.scss
- lib/ama/styles/version.rb
🎨 
[VSTS](https://amaabca.visualstudio.com/driver_education_backlog/_workitems?id=892&_a=edit)
This PR does 3 things:
1. It changes `.section__heading--no-bg` so that the text colour is darker (Charcoal, #656565) to bump up the hierarchy of our section__headings when they are outside of a background. 
2. It creates a `.button-grouping__button--disabled` class which will add the `not-allowed` cursor to `.button-grouping__button`s which we want to disable.
3. It creates a new way to use our checkboxes inside of a table. It is hiding the input border and background, and repositions the checkboxes themselves.
**1 & 2 Before:**
**1 & 2 After:**
**3 Desktop**
**3 Tablet**
**3 Mobile**
> Vsts 892 initial checkbox

- app/assets/stylesheets/layout_components/buttons/buttons.scss
- app/assets/stylesheets/layout_components/callouts/quote-callout.scss
- lib/ama/styles/version.rb
:art:
* Revisit the way that we present the final quote page to the user.
Instead of using Foundation's equalizer to create 2 equal height
columns, use flexbox.
* Instead of rendering an SVG node for the arrow on the quote page,
use plain CSS. This is much more simple and we can now use
relative positioning to simplify the process.
SEE: https://amaabca.visualstudio.com/insurance_backlog/_workitems?id=675
- ~I've added new components to the style guide (or have a PR in to add them).~
> VSTS-675 - Dynamic Auto Quote

- app/assets/stylesheets/layout_components/comparison-radios.scss
- lib/ama/styles/version.rb
:art:
removing negative margin which causes checkboxes to go outside of the container on smaller screen sizes.
this fixes the issue brought up in this pr: https://github.com/amaabca/membership/pull/837
~~- [ ] I've proof-read all text for legibility, proper grammar, punctuation, and capitalization (titlecase).~~
~~- [ ] I’ve linked to any relevant VSTS tickets~~
> removing negative margin 

- ama_styles.gemspec
- lib/ama/styles/version.rb
🐘 
Freezing version of  autoprefixer-rails to 8.6.4 which is working with older version of Node.js - 9.0. 
Removing emails which are not in use any more.
- ~[ ] I've added new components to the style guide (or have a PR in to add them).~
- ~[ ] I've tested on mobile, tablet, and desktop, as well as across all of the browsers we support.~
- ~[ ] I’ve linked to any relevant VSTS tickets~
> Fix version  autoprefixer-rails

- app/assets/stylesheets/layout/helper-classes.scss
- app/assets/stylesheets/layout_components/breadcrumbs.scss
- app/assets/stylesheets/layout_components/buttons/buttons.scss
- app/assets/stylesheets/layout_components/side_nav.scss
- app/assets/stylesheets/layout_components/siteheader.scss
- lib/ama/styles/version.rb
🎨 
There are a few differences in how we are building our react apps that require some slight changes to how we are styling certain elements in our react apps. 
The big one is we are changing how we are using `<a>` tags in react apps, which means that for breadcrumbs, buttons, and some existing `<a>` tags without a 'href' destination, the styles were breaking. 
pulls styles from: https://github.com/amaabca/react-kart/blob/master/src/App.scss
These shouldn't affect any existing styles in our rails apps.
[VSTS 18371](https://amaabca.visualstudio.com/roadside_backlog/_workitems/edit/18371)
> VSTS 18371 - Adds styles from our react apps.

- app/assets/stylesheets/layout_components/side_nav.scss
- lib/ama/styles/version.rb
This PR adds a missing hover state to side nave link, see screenshots below:
Before:
After:
> adds missing hover state to side nave link

- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/version.rb
- make the `::before` button sit in the middle of the radio button container
- make the `::after` button sit in the middle of the ::before button
- move the text over a little as it was crowding the button
VSTS: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/165
> VSTS-165 - fix radio button select alignment

- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/version.rb
- Make the checkmark for the checkboxes top:50%; instead of an explicit value. That way it displays correctly on checkboxes with multiple lines of text.
VSTS: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/165
> Checkbox Fix

- app/assets/stylesheets/foundation_and_overrides.scss
- app/assets/stylesheets/layout_components/data-table.scss
- app/assets/stylesheets/layout_components/index.scss
- lib/ama/styles/version.rb
* Include the styles for foundation pagination - we were previously
never using them across the Online Account.
* Add in minimal style code adapted from the jquery-datatables
gem that extends the foundation pagination styles for the
datatables context.
* Add a data-table component that is fully namespaced for a
data table context.
* Update minor version to indicate a non-breaking addition.
SEE: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/86
> ADO-86 - Pagination/DataTables

- app/assets/stylesheets/layout_components/buttons/button-grouping.scss
- lib/ama/styles/version.rb
* Add a `full` modifier to the button grouping elements so that
we can allow the box to expand to the full height of the container
(i.e. when using Foundation's equalizer).
SEE: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/2646
> ADO-2646 - RSA Appointments

- app/assets/stylesheets/layout_components/chat-widget.scss
- app/assets/stylesheets/layout_components/index.scss
- lib/ama/styles/version.rb
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/2501
We need to style the purecloud chat widget to look more like "AMA"
All classes are created by purecloud and I basically just have to overwrite them, there were a few times that using !important was necessary because of this.
This PR is also connected to this one: https://github.com/amaabca/membership/pull/939
Staging: https://stage-membership.ama.ab.ca/
> ADO-2501 Chat Widget AMA Branding Deploy to Production

- app/assets/stylesheets/layout_components/forms.scss
- lib/ama/styles/version.rb
* There are instances where we have a large amount of text in a
checkbox label and we may want more than the default 85% of
the label width available to display the content.
SEE: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/4887
> ADO-4887 - Add "Full" Checkbox Label

- app/assets/stylesheets/v2/layout_components/buttons/button-grouping.scss
- app/assets/stylesheets/v2/layout_components/features.scss
- app/assets/stylesheets/v3/layout_components/buttons/button-grouping.scss
- app/assets/stylesheets/v3/layout_components/features.scss
See: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/12956
* when I had originally fixed a problem with webfonts asset-url
prefixes, I mistaken also prefixed the image asset-urls.
Images aren't versioned as they are part of the stylesheets
directory.
> ADO 12956: Versioned Assets - asset-url Image Fix

- ama_styles.gemspec
🐘 
Problem: many of our AMA applications could have a locked version of
font-awesome-sass from before we implemented ama_styles
Solution: This PR adds a minimum required version of font-awesome-sass
gem so that if any of our applications update ama_styles to version
3.2.0 they will be required to remove any Gemfile locks associated with
font-awesome-sass
- Add font-awesome-sass dependency to require greater than or equal to
version 5.0.6 which changed the icon helper method `icon` to require
and additional param of style and started to use font-awesome 5
See:
https://github.com/FortAwesome/font-awesome-sass/commit/56136a6d8699ef4469e8b0ac9168d608ea6f9cc0
for reference
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13019
> ADO-13019-font-awesome-sass dep. min requirement

- app/assets/stylesheets/v3/layout_components/icon-info-box.scss
- app/assets/stylesheets/v3/layout_components/sections.scss
- app/assets/stylesheets/v3/layout_components/side_nav.scss
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13531
Styles the icon info box. Also makes some changes to section headers for some old classes that are still used in a few places.
New Style:
Old Style: 
> Ado 12959 icon info box

- app/assets/stylesheets/v3/layout_components/link-list.scss
- app/assets/stylesheets/v3/layout_components/member-info-card.scss
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13536
Styles the member info card, and adds a small fix that was missed on link lists.
New Style:
Old Style:
> styling member info card, adding fix that was missed on link lists

- lib/ama/styles/globals.rb
- lib/ama/styles/resolver.rb
- lib/ama/styles/version.rb
- spec/lib/ama/styles/resolver_spec.rb
See: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/12948
* We'll now be able to leverage a cache entry to pull the current
ama_styles version for all applications. The implications of
this is that we can roll out a version change with a single
PR and deployment.
> ADO 12948: Better Versioning

- app/assets/stylesheets/v2/layout_components/buttons/buttons.scss
- app/assets/stylesheets/v3/layout_components/buttons/buttons.scss
- lib/ama/styles/version.rb
https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/13397
Adds disabled state styling to all button colours in v2 and v3.
> adds disabled styling for all button colours, in v2 and v3

- README.md
- app/assets/stylesheets/v3/layout_components/cart.scss
- lib/ama/styles/version.rb
🎨
- update readme to reflect the removal of fa javascripts
- remove before on the accordion-toggle-icon for v3 which was added
because the html fa pro icon was not showing at the time, this issue
has been resolved with the fa pro kit available via the ama_layout gem
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_boards/board/t/Red%20Team/Stories/?workitem=14090
With the before removal, shows only one arrow
> ADO-14090 Cart bug fix, cleanup

- lib/ama/styles/resolver.rb
- lib/ama/styles/version.rb
- spec/lib/ama/styles/resolver_spec.rb
See: https://dev.azure.com/AMA-Ent/AMA-Ent/_workitems/edit/14330
* allow version override so that apps that have some assets on v2
and others on v3 will work
> ADO 14330: Allow Version Override

- app/assets/stylesheets/v2/layout_components/chat-widget.scss
- lib/ama/styles/version.rb
🎨
- Added CSS to hide the Cancel button from showing because if a user presses the cancel button from inside the DEPEA webview the cancel button will not interact with the mobile app, so the user is just left looking at a message that says the agent will be right with them.
**Before:**
**After:**
ADO LINK: https://dev.azure.com/AMA-Ent/AMA-Ent/_boards/board/t/Red%20Team/Stories/?workitem=10169
> ADO-10169 Remove Cancel Button Showing

- ama_styles.gemspec
- lib/ama/styles/version.rb
🐘
- using the font-awesome-sass gem above 5.15.1 in a application using the ama_styles gem will break the test suite
- locked gemspec file to font-awesome-sass <= 5.15.1
- updated version
ADO LINK:
https://dev.azure.com/AMA-Ent/AMA-Ent/_boards/board/t/Red%20Team/Stories/?workitem=72417
AB#72417
> 72417 - Lock font-awesome-sass gem to use <= 5.15.1
